Associations Project: Private Events
wintan1418/private-events pull request #2
Opened 2021-03-03 18:45 UTC by Leandro-Barretoo

In this project, the associations were the main goal to achieve and contains:
many-to-one between User(creator) and Event (on the creation of the event)
many-to-many between User(attendee) and Event(attended_event)

ps: if you run `rspec` to run RSpec and didn't work, try bundle exec `rspec`

2021-03-04 00:31 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUESTED🛑🛑**

Hello team,
Great work. All I can say is congrats. Great implementation of the project and it is professional looking.

Let's make some few changes to get it approved.

[REQUIRED]: In the event controller, index method, put two variables to implement the scopes you defined in the event model. e.g: @past_events, @future_events.

[REQUIRED]: The attend button is crashing. Kindly check it out

[REQUIRED]: The logout button is crashing. Kindly fix it.

[REQUIRED]: In the users controller, in the show method, specify variable for showing previous events attended by current_user and events he/she will attend in the future

Kindly make the requested changes and ask for another review👌👍

Happy coding💻💻💻💻

2021-03-05 18:16 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Excellent progress so far.  Both of you have done well on this project.
Let's make a few changes, and we will be done.

- [ ] Let's maintain a RESTful route by ensuring we are only exposing the available routes to our users. Since your `users_controller` only has `new, create and delete` action. 
Set `resources :users, only: [:new, :create, :show]

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)

I have gone ahead and made some comments on your codebase:

- [ ] Do not forget to add `yarn` to your getting started instructions, perfect after the `bundle install`. I couldn't run the project without running `yarn`

My personal highlights: I know sometimes it feels like a waste of time to pay attention to front-end design when you are been tested on backend stuff. Constant practice on this little UI does help serve as a consistent practice. Projects become appealing to check out even though it's doing just a little. Always try as much
### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/) as possible to pay attention to your UI, just a little while doing your projects here.

2021-03-05 18:16 UTC, acushlakoncept commented on app/views/events/index.html.erb
> +<% end %>
There should be absolutely NO logic in views.

2021-03-05 18:16 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
>      <%= yield %>
There should be absolutely NO logic in views.

2021-03-05 18:16 UTC, acushlakoncept commented on app/views/shared/_navb.html.erb
> +        <% end %>
There should be absolutely NO logic in views.

2021-03-06 13:11 UTC, Leandro-Barretoo commented
I need the logic in the view. The rest is fixed

2021-03-06 14:51 UTC, mke2111 requested changes
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @Leandro-Barretoo & @wintan1418, 👋🏽 
 **Thank you for the good job you got going on.** Your app works just fine.

## REQUIRED CHANGES

- [ ] Kindly move all the logic from the view files. Transfer them to the helpers folder. You can go ahead and create methods that you will call in the view files to provide the same functionality.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

2021-03-17 10:52 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- Good progress :+1: 
- No inline comment :+1: 
- No logic in your view :100: 

To Improve :factory_worker:

- [ ] It will be nice if you add `.stylelintrc.json` in your project as  it represent style guidelines that you share with your team - which is a group of all Microverse students.
- [ ] It will be good if `create` button is not displayed when user is not signed-in in order to make your app more intuitive:
![2](https://user-images.githubusercontent.com/58552748/111454958-4d47f300-8726-11eb-844c-66fd38fa55e7.png)

- [ ] Please add link that leads to the page where user can attend one event because your APP has to display all list of attendants in the event's show page, I think, it will be nice if there is a page that gives user opportunity to attend one event.
- [ ] I got this error when I run your APP, please add this command `yarn install` in your readme file, before `rails server` to make sure that `application.js` is present in your APP
![1](https://user-images.githubusercontent.com/58552748/111455475-e70fa000-8726-11eb-8a71-7600234204d9.gif)

- [ ] Some of your tests don't pass, it means that there are some bugs in your APP please, make sure to fix it
![1](https://user-images.githubusercontent.com/58552748/111456120-a6fced00-8727-11eb-91c3-9ad8ecd7fb4b.gif)

![1](https://user-images.githubusercontent.com/58552748/111456196-c0059e00-8727-11eb-849f-af57a6c371d9.gif)

![1](https://user-images.githubusercontent.com/58552748/111456273-d875b880-8727-11eb-89bf-3d2fbda374d8.gif)

![1](https://user-images.githubusercontent.com/58552748/111456326-ed524c00-8727-11eb-9d8f-879e55823245.gif)

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-03-17 16:12 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
- [ ] You have on failing test case: `rspec ./spec/event_spec.rb:73 # Events when a user attends an event`
- [ ] On clicking the `Attend` button, I got this error.
![review](https://user-images.githubusercontent.com/19773024/111499863-70899700-8754-11eb-96b9-5a7b1fea6ebc.jpg)
Right now a user can attend an event that doesn't exist. This is probably the reason for that error. Make sure a user can attend an event that was created by other users.


### Martin Afani 
#### Slack: whiz25

2021-03-17 21:05 UTC, SmithVyne requested changes
### Changes required 🤕 👍 
Hello, most of your project works fine but I can't find a button or link that a user can click to attend an event. 

![image](https://user-images.githubusercontent.com/31161701/111538370-a55e1400-877d-11eb-94b8-0af270bc6509.png)


[OPTIONAL] - I think you should add a link to the create new event page on the index page

2021-03-18 08:10 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @wintan1418  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] When a user is added to the past event (means list of already attended events), and when they try to browse the `myEvents` , the app crashes with the error on the screenshot 

![Screenshot from 2021-03-16 13-16-50](https://user-images.githubusercontent.com/56886064/111591703-7a50e000-87d0-11eb-98ed-02f18aaed751.png)

- [ ] Navigation links are present at the top of the page => The new_event and all_events link is missing from the top of the page
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-03-18 08:46 UTC, wintan1418 commented
hy Mugirase Emmanuel (descholar),,you have  an idea of how i can get to solve this issue,and also this error you are getting,I checked through and I saw that you are getting it from app/views/shared/table.html.erb,but in my shares directory ,I don't have any table.html.erb

2021-03-18 10:15 UTC, descholar-ceo commented
> hy Mugirase Emmanuel (descholar),,you have an idea of how i can get to solve this issue,and also this error you are getting,I checked through and I saw that you are getting it from app/views/shared/table.html.erb,but in my shares directory ,I don't have any table.html.erb

Hello @wintan1418 I do appologise for sending you a wrong screenshot, I have just updated the comment, you can check the screenshot again: ![Screenshot from 2021-03-18 12-13-51](https://user-images.githubusercontent.com/56886064/111609922-75495c00-87e3-11eb-978c-414fd8758309.png)

2021-03-18 10:23 UTC, wintan1418 commented
i have done the corrections,waiting for a review

2021-03-18 11:28 UTC, oloomoses approved these changes
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

2021-03-18 11:34 UTC, wintan1418 commented
hallelujah,thanks to all you TSE, though frustrating at some point.

2021-03-18 11:34 UTC, merged